
---
# https://eslint.org/docs/user-guide/configuring#specifying-environments

env:
  node: true

extends:
  - "airbnb-base"

rules:
  linebreak-style: 0
  no-console: 0
  import/extensions:
    - error
    - ignorePackages